### PR TITLE
Implement a lot of XCB functionality

### PR DESCRIPTION
**Pull request by zhmylove**
**Motivation**

Currently I'm working on my [WM](https://github.com/zhmylove/korgwm) written in Perl and X11::XCB lacked a lot of functionality for that. So I suggest this changes to make it usable.
Commit messages looks (to me) pretty self-descriptive, but I present them below in historical order with several comments.

**Changes**

* Fix type cast for ClientMessage data

   There is a warning during compilation with recent compilers, so I added an explicit type cast.

* Add RandR support

   This commit adds _most of_ RandR extension support. There are several `randr` types, specifically `struct randr_get_provider_property_reply`, `mode_info_t`, `transform_t`, `monitor_info_t` which I still not included into a `typemap`, so these functions are not implemented: `randr_create_mode`, `randr_set_monitor`, `randr_set_crtc_transform`. Read-only RandR support is better than nothing, huh? :)

* Implement xcb_get_setup

   It looks like it's missing in xml and `_GenerateMyXS.pm` does not see it so I've added it manually.

* Implement X11::XCB::Connection::get_keymap in XCB.xs

   X11 keymap is being received in several steps: at first we should call `xcb_get_setup()` and then `xcb_get_keyboard_mapping()`. The latter returns data (like several other XCB functions) via accessors (`xcb_get_keyboard_mapping_keysyms` in this case). In order to simplify Keymap requests from Perl, I've implemented new function in `Connection.pm` which just returns an array with keysyms. POD is updated correspondingly.

* Implement xcb_request_check and xcb_change_window_attributes_checked

   There was a _TODO_ to implement `*_checked` requests as they're missing in xml. I've implemented one of them and `xcb_request_check()` itself.

* Add ConfigureRequest and MapRequest events

   Just added some events into XCB.xs and made Moos-ish interface for them. Same for other "Add * event(s)" below.

* Add KeyPress and KeyRelease events

* Add CreateNotify, ConfigureNotify, UnmapNotify, DestroyNotify events

* Add EnterLeaveNotify event

* Add XKB support

   Like with RandR, _most of_ X11 XKEYBOARD extension functionality is implemented. I didn't add an xkb typemap for `xcb_xkb_action_t`, so `xcb_xkb_set_behavior()` and `xcb_xkb_sym_interpret()` are not implemented yet. The other functionality looks working good. I did check for `xkb_get_state()` and Xkb events.

* Implement PropertyNotify and fix missing pad0

   After adding Xkb support I revealed that some extensions could pass vital data through `pad0` field of the event. So I added this field to be more aligned with X11 protocol. Also this commit adds PropertyNotify event.

* Implement set_flags() for X11_XCB_ICCCM_WMHintsPtr

   It looks like current implementation of X11::XCB::ICCCM::WMHints was created only for read-only purposes, so I added `set_flags()` to allow change the internal state of `WMHintsPtr` object from Perl. 

* Add MotionNotify event

* Implement X11::XCB::Connection::get_query_tree_children in XCB.xs

   As XCB replies on `get_query_tree` with accessor `get_query_tree_children`, I've added a simple wrapper that makes possible to get an array with children IDs' in a single call from Perl.

* Add ButtonPressRelease event

* Bump version to 0.20

   I took the liberty to update the version. I hope, it worth it if you accept my PR.

Many thanks!

### CODE REVIEW

**Comment by pyih** [comment]
SO cool!

**Comment by stapelberg** [comment]
FWIW, if you intend to submit more changes in the future, it might be better to fork this module.

At this point, I’m only keeping it alive to support the i3 testsuite.

Have you checked if the i3 testsuite still passes with X11::XCB with your changes applied?

**Comment by zhmylove** [comment]
Thanksoff-by: Viacheslav Mitrofanov [v.v.mitrofanov@yadro.com](mailto:v.v.mitrofanov@yadro.com)
Signed-off-by: Nikita Shubin [n.shubin@yadro.com](mailto:n.shubin@yadro.com) Michael! 

Yes, I've checked the code against i3/testcases and single test fails for next and the same one for 4.22.
But I do not think it is related to X11::XCB.
It more looks like something with my setup and versions of Perl/TAP::Formatter::Base:

```
korg@ya:~/src/i3/build$ perl -e 'use TAP::Formatter::Base 99'
TAP::Formatter::Base version 99 required--this is only version 3.44 at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
korg@ya:~/src/i3/build$ perl -v

This is perl 5, version 36, subversion 0 (v5.36.0) built for x86_64-linux-gnu-thread-multi
...
```

Testsuite outputs:
<details>
<summary>For 4.22</summary>

  Console output:

    korg@ya:~/src/i3$ git clean -fdx
    korg@ya:~/src/i3$ git status
    HEAD detached at 4.22
    nothing to commit, working tree clean
    korg@ya:~/src/i3$ mkdir build && cd build && meson ..
    The Meson build system
    Version: 1.2.1
    Source dir: /home/korg/src/i3
    Build dir: /home/korg/src/i3/build
    Build type: native build
    Project name: i3
    Project version: 4.22
    C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
    C linker for the host machine: cc ld.bfd 2.40
    Host machine cpu family: x86_64
    Host machine cpu: x86_64
    Compiler for C supports arguments -Wunused-value: YES 
    Checking for function "strndup" : YES 
    Checking for function "mkdirp" : NO 
    Configuring config.h.in using configuration
    Found git repository at /home/korg/src/i3
    WARNING: You should add the boolean check kwarg to the run_command call.
             It currently defaults to false,
             but it will default to true in future releases of meson.
             See also: https://github.com/mesonbuild/meson/issues/9300
    Library m found: YES
    Library rt found: YES
    Library iconv found: NO
    Found pkg-config: /usr/bin/pkg-config (1.8.1)
    Run-time dependency libstartup-notification-1.0 found: YES 0.12
    Run-time dependency xcb found: YES 1.15
    Run-time dependency xcb-xkb found: YES 1.15
    Run-time dependency xcb-xinerama found: YES 1.15
    Run-time dependency xcb-randr found: YES 1.15
    Run-time dependency xcb-shape found: YES 1.15
    Run-time dependency xcb-util found: YES 0.4.0
    Run-time dependency xcb-cursor found: YES 0.1.4
    Run-time dependency xcb-keysyms found: YES 0.4.0
    Run-time dependency xcb-icccm found: YES 0.4.1
    Run-time dependency xcb-xrm found: YES 1.0
    Run-time dependency xkbcommon found: YES 1.5.0
    Run-time dependency xkbcommon-x11 found: YES 1.5.0
    Run-time dependency yajl found: YES 2.1.0
    Run-time dependency libpcre2-8 found: YES 10.42
    Run-time dependency cairo found: YES 1.16.0
    Run-time dependency pangocairo found: YES 1.50.14
    Run-time dependency glib-2.0 found: YES 2.77.2
    Run-time dependency gobject-2.0 found: YES 2.77.2
    Library ev found: YES
    Program perl found: YES (/usr/bin/perl)
    Program generate-command-parser.pl found: YES (/home/korg/src/i3/generate-command-parser.pl)
    Run-time dependency threads found: YES
    Program bash found: YES (/usr/bin/bash)
    Build targets in project: 17
    
    i3 4.22
    
        build docs (-Ddocs)    : False
        build manpages (-Dmans): False
    
    Found ninja-1.11.1 at /usr/bin/ninja
    WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.                                                       
    korg@ya:~/src/i3/build$ ninja
    [44/108] Generating anyevent-i3 with a custom command
    Checking if your kit is complete...
    Looks good
    Generating a Unix-style Makefile
    Writing Makefile for AnyEvent::I3
    Writing MYMETA.yml and MYMETA.json
    cp lib/AnyEvent/I3.pm blib/lib/AnyEvent/I3.pm
    Manifying 1 pod document
    [108/108] Linking target i3bar
    korg@ya:~/src/i3/build$ ./complete-run.pl 
    Running tests under Xvfb display :99
    Starting 24 Xephyr instances, starting at :1026...
    Use of uninitialized value $timingsjson in numeric gt (>) at ./complete-run.pl line 206.
    Writing logfile to 'testsuite-2023-09-19-15-36-59-4.22/complete-run.log'...
    [:1026] /home/korg/src/i3/testcases/t/547-nested-variables.t: finished
    [:1027] /home/korg/src/i3/testcases/t/525-i3bar-mouse-bindings.t: finished
    [:1028] /home/korg/src/i3/testcases/t/257-keypress-group1-fallback.t: finished
    [:1029] /home/korg/src/i3/testcases/t/544-focus-multiple-outputs.t: finished
    [:1030] /home/korg/src/i3/testcases/t/549-focus-wrapping-gaps.t: finished
    [:1031] /home/korg/src/i3/testcases/t/258-keypress-release.t: finished
    [:1032] /home/korg/src/i3/testcases/t/286-root-window-mouse-binding.t: finished
    [:1033] /home/korg/src/i3/testcases/t/542-layout-restore-remanage.t: finished
    [:1034] /home/korg/src/i3/testcases/t/291-swap.t: finished
    [:1035] /home/korg/src/i3/testcases/t/313-include.t: finished
    [:1036] /home/korg/src/i3/testcases/t/543-move-workspace-to-multiple-outputs.t: finished
    [:1037] /home/korg/src/i3/testcases/t/533-randr15.t: finished
    [:1038] /home/korg/src/i3/testcases/t/529-net-wm-desktop.t: finished
    [:1039] /home/korg/src/i3/testcases/t/548-motif-hints.t: finished
    [:1040] /home/korg/src/i3/testcases/t/308-focus_wrapping.t: finished
    [:1041] /home/korg/src/i3/testcases/t/535-workspace-next-prev.t: finished
    [:1042] /home/korg/src/i3/testcases/t/540-sigterm-cleanup.t: finished
    [:1043] /home/korg/src/i3/testcases/t/290-keypress-numlock.t: finished
    [:1044] /home/korg/src/i3/testcases/t/301-shape.t: finished
    [:1045] /home/korg/src/i3/testcases/t/298-ipc-misbehaving-connection.t: finished
    [:1046] /home/korg/src/i3/testcases/t/528-workspace-next-prev-reversed.t: finished
    [:1047] /home/korg/src/i3/testcases/t/316-drag-container.t: finished
    [:1048] /home/korg/src/i3/testcases/t/297-scroll-tabbed.t: finished
    [:1049] /home/korg/src/i3/testcases/t/541-resize-set-tiling.t: finished
    completed 269 of 270 tests
    
    #   Failed test 'font ok'
    #   at /home/korg/src/i3/testcases/t/317-bar-config-font-order.t line 37.
    #          got: '-misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1'
    #     expected: 'fixed'
    
    
    Test Summary Report
    -------------------
    Use of uninitialized value in subtraction (-) at /usr/share/perl/5.36/TAP/Formatter/Base.pm line 386.
    Negative repeat count does nothing at /usr/share/perl/5.36/TAP/Formatter/Base.pm line 386.
    /home/korg/src/i3/testcases/t/317-bar-config-font-order.t (Wstat: 0 Tests: 1 Failed: 1)
      Failed test:  1
    Files=270, Tests=3923, 11 wallclock secs ( 1.18 usr +  0.13 sys =  1.31 CPU)
    Result: FAIL
    
    The slowest tests are:
    	/home/korg/src/i3/testcases/t/316-drag-container.t with 7.18 seconds
    	/home/korg/src/i3/testcases/t/525-i3bar-mouse-bindings.t with 6.89 seconds
    	/home/korg/src/i3/testcases/t/297-scroll-tabbed.t with 6.66 seconds
    	/home/korg/src/i3/testcases/t/301-shape.t with 5.77 seconds
    	/home/korg/src/i3/testcases/t/286-root-window-mouse-binding.t with 5.40 seconds
    korg@ya:~/src/i3/build$ perl -MX11::XCB -le 'print X11::XCB->VERSION'
    0.20
</details>

<details>
<summary>For latest next (bffa4a543c492f8bc6121143b7342d1488ff5fa0)</summary>

  Console output:

```
korg@ya:~/src/i3$ git clean -fdx
korg@ya:~/src/i3$ git status
On branch next
Your branch is up to date with 'origin/next'.

nothing to commit, working tree clean
korg@ya:~/src/i3$ mkdir build && cd build && meson ..
The Meson build system
Version: 1.2.1
Source dir: /home/korg/src/i3
Build dir: /home/korg/src/i3/build
Build type: native build
Project name: i3
Project version: 4.22
C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
C linker for the host machine: cc ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wunused-value: YES 
Checking for function "strndup" : YES 
Checking for function "mkdirp" : NO 
Configuring config.h.in using configuration
Found git repository at /home/korg/src/i3
Library m found: YES
Library rt found: YES
Library iconv found: NO
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Run-time dependency libstartup-notification-1.0 found: YES 0.12
Run-time dependency xcb found: YES 1.15
Run-time dependency xcb-xkb found: YES 1.15
Run-time dependency xcb-xinerama found: YES 1.15
Run-time dependency xcb-randr found: YES 1.15
Run-time dependency xcb-shape found: YES 1.15
Run-time dependency xcb-util found: YES 0.4.0
Run-time dependency xcb-cursor found: YES 0.1.4
Run-time dependency xcb-keysyms found: YES 0.4.0
Run-time dependency xcb-icccm found: YES 0.4.1
Run-time dependency xcb-xrm found: YES 1.0
Run-time dependency xkbcommon found: YES 1.5.0
Run-time dependency xkbcommon-x11 found: YES 1.5.0
Run-time dependency yajl found: YES 2.1.0
Run-time dependency libpcre2-8 found: YES 10.42
Run-time dependency cairo found: YES 1.16.0
Run-time dependency pangocairo found: YES 1.50.14
Run-time dependency glib-2.0 found: YES 2.77.2
Run-time dependency gobject-2.0 found: YES 2.77.2
Library ev found: YES
Program perl found: YES (/usr/bin/perl)
Program generate-command-parser.pl found: YES (/home/korg/src/i3/generate-command-parser.pl)
Run-time dependency threads found: YES
Program bash found: YES (/usr/bin/bash)
Build targets in project: 17

i3 4.22

    build docs (-Ddocs)    : False
    build manpages (-Dmans): False

Found ninja-1.11.1 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.                                                       
korg@ya:~/src/i3/build$ ninja
[36/108] Generating anyevent-i3 with a custom command
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for AnyEvent::I3
Writing MYMETA.yml and MYMETA.json
cp lib/AnyEvent/I3.pm blib/lib/AnyEvent/I3.pm
Manifying 1 pod document
[108/108] Linking target i3-config-wizard
korg@ya:~/src/i3/build$ ./complete-run.pl 
Running tests under Xvfb display :99
Starting 24 Xephyr instances, starting at :1026...
Use of uninitialized value $timingsjson in numeric gt (>) at ./complete-run.pl line 206.
Writing logfile to 'testsuite-2023-09-19-15-39-07-4.22-48-gbffa4a54/complete-run.log'...
[:1026] /home/korg/src/i3/testcases/t/258-keypress-release.t: finished
[:1027] /home/korg/src/i3/testcases/t/547-nested-variables.t: finished
[:1028] /home/korg/src/i3/testcases/t/544-focus-multiple-outputs.t: finished
[:1029] /home/korg/src/i3/testcases/t/286-root-window-mouse-binding.t: finished
[:1030] /home/korg/src/i3/testcases/t/543-move-workspace-to-multiple-outputs.t: finished
[:1031] /home/korg/src/i3/testcases/t/535-workspace-next-prev.t: finished
[:1032] /home/korg/src/i3/testcases/t/290-keypress-numlock.t: finished
[:1033] /home/korg/src/i3/testcases/t/540-sigterm-cleanup.t: finished
[:1034] /home/korg/src/i3/testcases/t/548-motif-hints.t: finished
[:1035] /home/korg/src/i3/testcases/t/298-ipc-misbehaving-connection.t: finished
[:1036] /home/korg/src/i3/testcases/t/525-i3bar-mouse-bindings.t: finished
[:1037] /home/korg/src/i3/testcases/t/549-focus-wrapping-gaps.t: finished
[:1038] /home/korg/src/i3/testcases/t/538-i3bar-primary-output.t: finished
[:1039] /home/korg/src/i3/testcases/t/529-net-wm-desktop.t: finished
[:1040] /home/korg/src/i3/testcases/t/546-empty-bindcommand.t: finished
[:1041] /home/korg/src/i3/testcases/t/320-mouse-bindings.t: finished
[:1042] /home/korg/src/i3/testcases/t/308-focus_wrapping.t: finished
[:1043] /home/korg/src/i3/testcases/t/301-shape.t: finished
[:1044] /home/korg/src/i3/testcases/t/547-explicit-mode-default.t: finished
[:1045] /home/korg/src/i3/testcases/t/297-scroll-tabbed.t: finished
[:1046] /home/korg/src/i3/testcases/t/533-randr15.t: finished
[:1047] /home/korg/src/i3/testcases/t/541-resize-set-tiling.t: finished
[:1048] /home/korg/src/i3/testcases/t/316-drag-container.t: finished
[:1049] /home/korg/src/i3/testcases/t/257-keypress-group1-fallback.t: finished
completed 270 of 271 tests

#   Failed test 'font ok'
#   at /home/korg/src/i3/testcases/t/317-bar-config-font-order.t line 37.
#          got: '-misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1'
#     expected: 'fixed'


Test Summary Report
-------------------
Use of uninitialized value in subtraction (-) at /usr/share/perl/5.36/TAP/Formatter/Base.pm line 386.
Negative repeat count does nothing at /usr/share/perl/5.36/TAP/Formatter/Base.pm line 386.
/home/korg/src/i3/testcases/t/317-bar-config-font-order.t (Wstat: 0 Tests: 1 Failed: 1)
  Failed test:  1
Files=271, Tests=3954, 12 wallclock secs ( 1.16 usr +  0.13 sys =  1.29 CPU)
Result: FAIL

The slowest tests are:
	/home/korg/src/i3/testcases/t/525-i3bar-mouse-bindings.t with 7.58 seconds
	/home/korg/src/i3/testcases/t/320-mouse-bindings.t with 7.55 seconds
	/home/korg/src/i3/testcases/t/316-drag-container.t with 7.12 seconds
	/home/korg/src/i3/testcases/t/301-shape.t with 6.53 seconds
	/home/korg/src/i3/testcases/t/297-scroll-tabbed.t with 6.08 seconds
```

I'll try to look onto it soon.

**Comment by zhmylove** [comment]
@stapelberg 
UPD: I've updated the comment above with my findings of the failed test. Probably, the testcase should be changed in order to handle this [proper] situation correctly.

Dirty way:
```diff
--- a/testcases/t/317-bar-config-font-order.t
+++ b/testcases/t/317-bar-config-font-order.t
@@ -34,6 +34,8 @@ my $bars = $i3->get_bar_config()->recv;
 
 my $bar_id = shift @$bars;
 my $bar_config = $i3->get_bar_config($bar_id)->recv;
+$bar_config->{font} = 'fixed' if $bar_config->{font}
+    eq '-misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1';
 is($bar_config->{font}, 'fixed', 'font ok');
 
 done_testing;
```

More clean way:
```diff
--- a/testcases/t/317-bar-config-font-order.t
+++ b/testcases/t/317-bar-config-font-order.t
@@ -34,6 +34,11 @@ my $bars = $i3->get_bar_config()->recv;
 
 my $bar_id = shift @$bars;
 my $bar_config = $i3->get_bar_config($bar_id)->recv;
-is($bar_config->{font}, 'fixed', 'font ok');
+my $ok;
+$bar_config->{font} eq $_ and $ok = 1 for qw(
+    -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
+    fixed
+);
+is($ok, 1, 'font ok');
 
 done_testing;
```

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
> Could you consider giving me a comaint on CPAN in order to support this project with this particular name?
> For my part, I will take responsibility for ensuring that any new version of X11::XСB successfully passes all the test cases for the next branch of i3 and for the latest stable i3 release.

Sounds good! I granted you co-maintainer status on CPAN.

**Pull request merged**
